# MSW - My Scons Wrapper
# Shared library generation.
# This file used to compile current package outside main build system frame
#
# @author Victor Garcia <vichor@gmail.com>
# @date 2011-05-29
# 

env = Environment()
debug = ARGUMENTS.get('debug', 0)
if int(debug):
    env.Append(CCFLAGS = '-g')

# Build package
SConscript( 'SConscript', exports='env')

# Build test
objects = Object('test/test.cpp', CPPPATH='.', CCFLAGS='-g')
Program ('testfndts',objects,LIBS=[ 'fndts', 'pthread' ], LIBPATH = [ '.' ], RPATH = [ '.' ])

